### PR TITLE
Email validation

### PR DESCRIPTION
**Pull request by michel-at-bubble**
allow addresses like name+test@domain.email

could be stricter on the allowance of dots and plusses, but for the sake of regex legibility I didnt go down that route.

### CODE REVIEW

**Review by gpr — APPROVED** [review]
Thanks for the patch!

**Comment by byrnesvictim** [comment]
Getting some conflict issues with a couple of the lines due to what looks like a corrupted character? Will look at adjusting the files in our next build to match manually, but at current cool+email@private.domain works everywhere I could find except registration page

**Comment by dannythunder** [comment]
Old PR, still active?

**Comment by byrnesvictim** [comment]
It can probably be closed, with so many other changes since then it might be safest anyway.

**Pull request closed without merging**
