### PR TITLE
Issue #19: more mobile-friendly interface for NAFLM

### PR DESCRIPTION
**Pull request by rythos42**
## Summary ##
This pull request is for a more mobile-friendly interface for NAFLM (issue #19). The regular interface is brilliant for use from a desktop, and even from larger tablets, but it's functionality suffers when attempting to use from a phone. There are 2 primary problems:

1. The team view is too wide, preventing users from being able to see both the player name/number and their stats at the same time.
1. The match view is too wide, preventing users from being able to see both the player name/number and the table header (`Td`, `Cp`, etc) at the same time. This is particularly difficult as it then requires a user to count down and across the table, which is very error prone, in order to input their match information. 
    
In this work, I attempted to distill the (very functional!) application down to the most important set of information for playing from a phone. This means:

1. That information that is critical to be able to *play a game*: player name, number, stats, skills, and SPP. It also includes more visible information on how many niggling injuries a player has, as well as any that are required to miss the next game.
1. That information that is critical to playing *the next game*: SPP scoring plays a player makes, fan factor gains/losses, treasury changes, skill-ups, injuries.
1. Score was also included. It isn't important to either of these, but it felt wrong not to include it!
    
    
This work was done in the following manner:

1. When possible, existing work was re-used. The application is mostly very well designed, so some functionality was very easy to re-use -- login, schedule a match, and all of the team management functionality.
1. When not possible, new mobile code was written. The team and match views needed UX work in order to better support mobile, and so had entirely new code written.

## Code ##
Most of the new work is contained in `lib/class_mobile_htmlout.php`, which outputs all of the `HTML` for the team and match views, as well as some `JavaScript` and `PHP` to knit it all together. 

There is a new start page for the mobile interface `mobile.php`. It takes no parameters by default, and can be addressed just by `http://localhost/mobile.php` and then login page will be displayed, or the team view if the user is already logged in.

2 "web service" classes were added - `team_webservice.php` and `match_webservice.php`, which allow `AJAX` calls to retrieve information where a postback was less ideal. These web services are new architecture for the system, and I'm not 100% on how I protected them. They currently check to see if the `Coach` is logged in, but it is possible that more is required.

`css/mobile.css` contains all of the CSS for the mobile interface. It changes the display for screens under 600px and is only loaded if the user starts from mobile.php, so it will have no effect on users not using the mobile start page. Most of the CSS in this file changes existing CSS from `stylesheet1.css` to reduce `padding`/`margin`, and to center items.

A new folder `js` keeps `JavaScript` files. Existing `JavaScript` has not been moved, but new files were placed here. I'm most familiar with KnockoutJS as an MVVM library for `JS`, so I used that here. `js/app/ViewModels ` contains JS code that modularizes interactive functionality. `js/lib/` contains the KnockoutJS library and UnderscoreJS.

`class_mobile.php` contains only 2 methods, which set and ask whether the application was started using the mobile start page. This is used in places throughout existing code to add new buttons or hide existing functionality where that code was re-used. 

There have been some other changes throughout other classes, like `class_player.php`, `class_team_htmlout.php`, `class_match_htmlout.php`. These changes were entirely refactoring to expose useful existing functionality. In some cases a method was returning a computed value, and that value was also assigned to a public field so that it could be used by json_encode, so it could be used by `JavaScript` code. There is an opportunity for this to have unknown "timing issues", but it works where I need it.

## Translations ##
Lastly, I used existing translations where ever possible, but there are 4 strings that I needed to make new. They are: "Miss next game", "may buy new skill", "Management", "for me, to". I didn't add these to translations.xml, because that file says to not touch it, and I didn't want to disobey. :)

## Future Work ##
I'm done with what I have on my todo list for this. I'm also getting into a pretty busy time for the next month, so unless there are concerns, bugs or "hey, wouldn't it be cool if...?" comments, this may be it for me for a little bit. :) At the same time, I enjoyed the hell out of this, and would definitely be interested in hacking away at that issue list a bit whenever I can find the time again. :)

### CODE REVIEW

**Comment by Shteve0** [comment]
So I rolled this in and deployed on thenafdev.obblm.com. How do I get it to
default for mobile?

Browsing right now on an android device. I can get to the login page via
/mobile.php, but as soon as I log in it kicks me back to full page view. Am
I missing something?

**Comment by rythos42** [comment]
That I can see, you aren't doing anything wrong. I also can't see what the issue might be. Using the immortal words -- "it works on my machine". :) thenafdev is also doing it wrong, even if you navigate to `mobile.php` from a desktop machine.

I have to run, but here's the flow that's supposed to happen:

Navigating to `mobile.php`, on line 58 is sets `Mobile::setIsMobile(true)`.
This sets a $_SESSION variable `isMobile` to true.
`sec_login()` is run from `sections.php`
Line 93 of `sections.php` echos `getFormAction()`
Line 31 checks `Mobile::isMobile()` and returns `mobile.php' or 'index.php`.

Check to see that `lib\class_mobile.php` exists on thenafdev?  The code on GitHub looks identical to what I have locally (also: git diff and a fork difference check confirms, mostly)

**Comment by williamleonard** [comment]
I didn't look at it fully, but with mobile.php being pretty close to what index.php and a session variable being set, why not try to combine this functionality into index.php?  Can you email me the root login for thenafdev so I can review and I can debug from the server side if needed.

Also does this work in handler.php?  What about the mobile check changing the theme?  I guess similar to being able to set the default theme to a custom theme, couldn't the mobile check just set the theme for the session?

Maybe I am way off, just some thoughts without digging through the code more deeply.

**Comment by Shteve0** [comment]
I think it may have been a problem when I updated the dev view - now appears to be working! 

On the face of it, I have to manually navigate to /mobile.php in order to get this view.  Once I log in it takes me to a team management page as per the screenshots.  

However, I can't navigate from there to see any other teams or tables, however; and there's no obvious way of getting out of mobile mode other than by going to /index.php manually (even requesting desktop site in my browser just refreshes mobile view).  Which is cool if I know that I have to do that, but I wonder if we might want to add a link to the bottom of the view that says "view full website" might be an idea.  I can then add a link to Mobile View somewhere in the menu structure?

**Comment by rythos42** [comment]
Alright, I'm working on some changes based on what you've said, but don't think I'll be able to get them done before next week. >.<

index.php and mobile.php are different in confusing ways, but I've combined them and added a GET parameter of "mobile=1".

I don't know anything about handler.php. I took a look at it, but couldn't see what it was about - what should I take into account there?

I was toying with adding a little menu after I added Management, but figured I had enough space. I'm now adding a little menu at the top right, containing "Management", "Desktop Site" and "Logout" links.

**Pull request merged**
